// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Dashboard

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Index
void ui_Index_screen_init(void);
lv_obj_t * ui_Index;
lv_obj_t * ui_topbar;
lv_obj_t * ui_time_value;
lv_obj_t * ui_wifi_icon;
lv_obj_t * ui_upload_icon;
lv_obj_t * ui_Sensor_Group;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Container3;
lv_obj_t * ui_temp_value;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Container2;
lv_obj_t * ui_humi_value;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Label14;
lv_obj_t * ui_pm25_value;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label11;
lv_obj_t * ui_pm10_value;
lv_obj_t * ui_Label12;
lv_obj_t * ui_pm100_value;
lv_obj_t * ui_Lamp_Group;
void ui_event_light1_sw(lv_event_t * e);
lv_obj_t * ui_light1_sw;
lv_obj_t * ui_Label1;
lv_obj_t * ui_light1_img;
void ui_event_light2_sw(lv_event_t * e);
lv_obj_t * ui_light2_sw;
lv_obj_t * ui_Label2;
lv_obj_t * ui_light2_img;
void ui_event_light3_sw(lv_event_t * e);
lv_obj_t * ui_light3_sw;
lv_obj_t * ui_Label3;
lv_obj_t * ui_light3_img;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_light1_sw(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_light1_img, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_light2_sw(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_light2_img, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_light3_sw(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_light3_img, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Index_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Index);
}
