// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Dashboard

#include "../ui.h"

void ui_Index_screen_init(void)
{
    ui_Index = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Index, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Index, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Index, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_Index, lv_color_hex(0xECF0F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Index, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Index, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Index, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topbar = lv_obj_create(ui_Index);
    lv_obj_set_height(ui_topbar, 50);
    lv_obj_set_width(ui_topbar, lv_pct(100));
    lv_obj_set_align(ui_topbar, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_topbar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_topbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_topbar, lv_color_hex(0x2ECC71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_topbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_topbar, lv_color_hex(0x3498DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_topbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_topbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_topbar, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_topbar, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_value = lv_label_create(ui_topbar);
    lv_obj_set_width(ui_time_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time_value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_time_value, "14:32:52");
    lv_obj_set_style_text_color(ui_time_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time_value, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_icon = lv_img_create(ui_topbar);
    lv_img_set_src(ui_wifi_icon, &ui_img_1756937144);
    lv_obj_set_width(ui_wifi_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi_icon, -44);
    lv_obj_set_y(ui_wifi_icon, 0);
    lv_obj_set_align(ui_wifi_icon, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_wifi_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_wifi_icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_wifi_icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_upload_icon = lv_img_create(ui_topbar);
    lv_img_set_src(ui_upload_icon, &ui_img_330755264);
    lv_obj_set_width(ui_upload_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_upload_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_upload_icon, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_upload_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_upload_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_upload_icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_upload_icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sensor_Group = lv_obj_create(ui_Index);
    lv_obj_remove_style_all(ui_Sensor_Group);
    lv_obj_set_width(ui_Sensor_Group, lv_pct(100));
    lv_obj_set_height(ui_Sensor_Group, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Sensor_Group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Sensor_Group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Sensor_Group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Sensor_Group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Sensor_Group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Sensor_Group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Sensor_Group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Sensor_Group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Sensor_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Sensor_Group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Sensor_Group);
    lv_obj_set_height(ui_Panel5, 120);
    lv_obj_set_flex_grow(ui_Panel5, 1);
    lv_obj_set_x(ui_Panel5, 0);
    lv_obj_set_y(ui_Panel5, 75);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel5, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel5, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel5, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Panel5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Panel5, lv_color_hex(0x34495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x2ECC71), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image4 = lv_img_create(ui_Panel5);
    lv_img_set_src(ui_Image4, &ui_img_temperatures_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 13);
    lv_obj_set_y(ui_Image4, 11);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image4, lv_color_hex(0x2C3E50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Image4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_Image4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Container4 = lv_obj_create(ui_Panel5);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container4, -15);
    lv_obj_set_y(ui_Container4, 0);
    lv_obj_set_align(ui_Container4, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, -1);
    lv_obj_set_align(ui_Container3, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temp_value = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_temp_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp_value, 88);
    lv_obj_set_y(ui_temp_value, 16);
    lv_label_set_text(ui_temp_value, "88.8");
    lv_obj_set_style_text_color(ui_temp_value, lv_color_hex(0x29CE73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp_value, &ui_font_Segment42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "°C");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x808B96), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -1);
    lv_obj_set_align(ui_Container2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humi_value = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_humi_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humi_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humi_value, 88);
    lv_obj_set_y(ui_humi_value, 16);
    lv_label_set_text(ui_humi_value, "88.8");
    lv_obj_set_style_text_color(ui_humi_value, lv_color_hex(0x3498DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humi_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humi_value, &ui_font_Segment42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "%RH");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x808B96), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Sensor_Group);
    lv_obj_set_height(ui_Panel6, 120);
    lv_obj_set_flex_grow(ui_Panel6, 1);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, 75);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel6, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel6, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel6, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Panel6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Panel6, lv_color_hex(0x34495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x2ECC71), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image5 = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_Image5, &ui_img_dust_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 13);
    lv_obj_set_y(ui_Image5, 11);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image5, lv_color_hex(0x2C3E50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Image5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_Image5, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Container1 = lv_obj_create(ui_Panel6);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container1, -15);
    lv_obj_set_y(ui_Container1, 0);
    lv_obj_set_align(ui_Container1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container5, 0);
    lv_obj_set_y(ui_Container5, -1);
    lv_obj_set_align(ui_Container5, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "PM2.5");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x808B96), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label14, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25_value = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_pm25_value, 70);
    lv_obj_set_height(ui_pm25_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25_value, 88);
    lv_obj_set_y(ui_pm25_value, 16);
    lv_label_set_long_mode(ui_pm25_value, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_pm25_value, "888");
    lv_obj_set_style_text_color(ui_pm25_value, lv_color_hex(0x29CE73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm25_value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25_value, &ui_font_Segment42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, -1);
    lv_obj_set_align(ui_Container6, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "PM1");
    lv_label_set_recolor(ui_Label11, "true");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x808B96), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label11, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10_value = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_pm10_value, 53);
    lv_obj_set_height(ui_pm10_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10_value, 88);
    lv_obj_set_y(ui_pm10_value, 16);
    lv_label_set_long_mode(ui_pm10_value, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_pm10_value, "888");
    lv_obj_set_style_text_color(ui_pm10_value, lv_color_hex(0x3498DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10_value, &ui_font_Segment32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "PM10");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x808B96), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm100_value = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_pm100_value, 53);
    lv_obj_set_height(ui_pm100_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm100_value, 88);
    lv_obj_set_y(ui_pm100_value, 16);
    lv_label_set_long_mode(ui_pm100_value, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_pm100_value, "888");
    lv_obj_set_style_text_color(ui_pm100_value, lv_color_hex(0xF1C40F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm100_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm100_value, &ui_font_Segment32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lamp_Group = lv_obj_create(ui_Index);
    lv_obj_remove_style_all(ui_Lamp_Group);
    lv_obj_set_width(ui_Lamp_Group, lv_pct(100));
    lv_obj_set_height(ui_Lamp_Group, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Lamp_Group, 0);
    lv_obj_set_y(ui_Lamp_Group, -1);
    lv_obj_set_align(ui_Lamp_Group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Lamp_Group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Lamp_Group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Lamp_Group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Lamp_Group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Lamp_Group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Lamp_Group, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Lamp_Group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Lamp_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Lamp_Group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light1_sw = lv_obj_create(ui_Lamp_Group);
    lv_obj_set_height(ui_light1_sw, 100);
    lv_obj_set_flex_grow(ui_light1_sw, 1);
    lv_obj_set_x(ui_light1_sw, 0);
    lv_obj_set_y(ui_light1_sw, 75);
    lv_obj_set_align(ui_light1_sw, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_light1_sw, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_light1_sw, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_light1_sw, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_light1_sw, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_light1_sw, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_light1_sw, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_light1_sw, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_light1_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_light1_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_light1_sw, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_light1_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_light1_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_light1_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_light1_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_light1_sw, lv_color_hex(0x34495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_light1_sw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_light1_sw, lv_color_hex(0x2ECC71), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_light1_sw, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_light1_sw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_light1_sw, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_light1_sw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_light1_sw, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label1 = lv_label_create(ui_light1_sw);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 13);
    lv_obj_set_y(ui_Label1, 13);
    lv_label_set_text(ui_Label1, "ไฟหน้า");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Kanit24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light1_img = lv_img_create(ui_light1_sw);
    lv_img_set_src(ui_light1_img, &ui_img_1821463755);
    lv_obj_set_width(ui_light1_img, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light1_img, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_light1_img, -10);
    lv_obj_set_y(ui_light1_img, -10);
    lv_obj_set_align(ui_light1_img, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_light1_img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_light1_img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_light1_img, lv_color_hex(0x34495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_light1_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_light1_img, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_light1_img, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_light2_sw = lv_obj_create(ui_Lamp_Group);
    lv_obj_set_height(ui_light2_sw, 100);
    lv_obj_set_flex_grow(ui_light2_sw, 1);
    lv_obj_set_x(ui_light2_sw, 0);
    lv_obj_set_y(ui_light2_sw, 75);
    lv_obj_set_align(ui_light2_sw, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_light2_sw, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_light2_sw, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_light2_sw, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_light2_sw, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_light2_sw, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_light2_sw, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_light2_sw, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_light2_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_light2_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_light2_sw, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_light2_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_light2_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_light2_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_light2_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_light2_sw, lv_color_hex(0x34495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_light2_sw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_light2_sw, lv_color_hex(0x2ECC71), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_light2_sw, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_light2_sw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_light2_sw, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_light2_sw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_light2_sw, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label2 = lv_label_create(ui_light2_sw);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 13);
    lv_obj_set_y(ui_Label2, 13);
    lv_label_set_text(ui_Label2, "ไฟกลาง");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Kanit24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light2_img = lv_img_create(ui_light2_sw);
    lv_img_set_src(ui_light2_img, &ui_img_1821463755);
    lv_obj_set_width(ui_light2_img, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light2_img, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_light2_img, -10);
    lv_obj_set_y(ui_light2_img, -10);
    lv_obj_set_align(ui_light2_img, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_light2_img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_light2_img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_light2_img, lv_color_hex(0x34495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_light2_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_light2_img, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_light2_img, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_light3_sw = lv_obj_create(ui_Lamp_Group);
    lv_obj_set_height(ui_light3_sw, 100);
    lv_obj_set_flex_grow(ui_light3_sw, 1);
    lv_obj_set_x(ui_light3_sw, 0);
    lv_obj_set_y(ui_light3_sw, 75);
    lv_obj_set_align(ui_light3_sw, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_light3_sw, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_light3_sw, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_light3_sw, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_light3_sw, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_light3_sw, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_light3_sw, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_light3_sw, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_light3_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_light3_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_light3_sw, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_light3_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_light3_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_light3_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_light3_sw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_light3_sw, lv_color_hex(0x34495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_light3_sw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_light3_sw, lv_color_hex(0x2ECC71), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_light3_sw, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_light3_sw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_light3_sw, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_light3_sw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_light3_sw, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label3 = lv_label_create(ui_light3_sw);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 13);
    lv_obj_set_y(ui_Label3, 13);
    lv_label_set_text(ui_Label3, "ไฟหลัง");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Kanit24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light3_img = lv_img_create(ui_light3_sw);
    lv_img_set_src(ui_light3_img, &ui_img_1821463755);
    lv_obj_set_width(ui_light3_img, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light3_img, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_light3_img, -10);
    lv_obj_set_y(ui_light3_img, -10);
    lv_obj_set_align(ui_light3_img, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_light3_img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_light3_img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_light3_img, lv_color_hex(0x34495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_light3_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_light3_img, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_light3_img, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_light1_sw, ui_event_light1_sw, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_light2_sw, ui_event_light2_sw, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_light3_sw, ui_event_light3_sw, LV_EVENT_ALL, NULL);

}
